language: node_js
node_js:
- 10.14.2
after_script:
- scp -o StrictHostKeyChecking=no dist/app.js root@39.96.48.75:/home/www/webpack-mpa
before_install:
- openssl aes-256-cbc -K $encrypted_945f488607d4_key -iv $encrypted_945f488607d4_iv
  -in ali_centos7.5_rsa.enc -out ~\/.ssh/ali_centos7.5_rsa -d
