language: node_js
node_js:
- 10.14.2

before_install:
- openssl aes-256-cbc -K $encrypted_945f488607d4_key -iv $encrypted_945f488607d4_iv
  -in ali_centos7.5_rsa.enc -out .travis/ali_centos7.5_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/ali_centos7.5_rsa
- ssh-add .travis/ali_centos7.5_rsa

script:
- npm run build
- npm run test

after_script:
- scp -r -o StrictHostKeyChecking=no dist/** root@39.96.48.75:/home/www/webpack-mpa